### ISSUE TITLE
Training of additional special tokens

### ISSUE THREAD

**Issue by WHB139426** [WisconsinAIVision/YoLLaVA#2]
Thanks for your great work.

In your paper, you mention that YoLLaVA only trains the additional tokens (e.g., <sks>, <token_i>) and lm_head matrix associated
with the identifier token <sks> only. 

However, how do you implement this freezing operation? I mean I can just freeze or unlock the **whole** embedding layer (nn.embedding in pytorch) and the lm_head (nn.Linear in pytorch). Can you provide the implementation of only freezing part of the nn.embedding and nn.Linear?

Thanks a lot!

**Comment by thaoshibe** [comment]
Hello,
The implementation is very similar to textual-inversion. We will update the whole embedding first, then restore the no-updating embedding indices.

Please refer to: https://github.com/WisconsinAIVision/YoLLaVA/blob/9810b53cc8e714de74d706c2565b74067ed435f9/train-multi-token.py#L198

Which I built upon this source code: https://github.com/huggingface/diffusers/blob/38a3e4df926c59bc122191c0fc8066755e98b6d2/examples/textual_inversion/textual_inversion.py#L908

Thank you~
