### ISSUE TITLE
Question about the epoch of the best checkpoint

### ISSUE THREAD

**Issue by chenyangzhu1** [WisconsinAIVision/YoLLaVA#5]
Thanks for your excellent work! 

I am curious about which epoch typically yields the best checkpoint during the training phase.

Thanks again!

**Comment by thaoshibe** [comment]
Hello, I found out that around 10-12 epochs are the best, generally.
In actual code, I save the best checkpoint by: (1) epoch > 4 and (2) yield best accuracy on recognition on train set. (here: https://github.com/WisconsinAIVision/YoLLaVA/blob/9810b53cc8e714de74d706c2565b74067ed435f9/train.py#L246)

Thank youu~
