### ISSUE TITLE
Negative Mined Images for Each Category

### ISSUE THREAD

**Issue by soroushseifi** [WisconsinAIVision/YoLLaVA#6]
Hi,
I am very interested about your work on personalization. I am currently trying to test different approaches with your dataset. I wonder if you could release the hard negative images you used for each object ?
For now in the repository I could only find examples for two of the objects <bo> and <mam>.

Thank you !

**Comment by thaoshibe** [comment]
Sure, I will update it in my Google Drive soon -- Actually I tried to test and release the image retrieval pipeline (which is from LAION) -- But it's not available anymore https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion5B-H-14&useMclip=false

**Comment by thaoshibe** [comment]
But I have the negative for all subjects ;) Will push soon~ Thank you for your patience~

**Comment by thaoshibe** [comment]
Hello, please download the negative examples here: https://github.com/WisconsinAIVision/YoLLaVA?tab=readme-ov-file#yollava-dataset

Thank youu :D
