### ISSUE TITLE
requirements/environment file is missing

### ISSUE THREAD

**Issue by IemProg** [WisconsinAIVision/YoLLaVA#7]
Hi @thaoshibe ,

Thank you for sharing such an interesting paper and publishing the code—it’s really appreciated!

Could you please, add the requirements.txt file, or the anaconda .yml file to install the necessary packages for the project ?

Thanks !

**Comment by thaoshibe** [comment]
Hi, thank you so much for your interest~ 💯 
This is built upon LLaVA, so please follow exactly LLaVA's install instruction: https://github.com/haotian-liu/LLaVA?tab=readme-ov-file#install

(I will put more details and pretrained checkpoints into this repo later; Thanks so much for your patience ;))
